AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  App:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      FunctionName: main
      Runtime: go1.x
      CodeUri: s3://poc-sandbox-fukuiretu-upload-test/lambda-go-sample/938d521b80e2c81315c2c3224bfe3398
      Timeout: 300
